CREATE OR REPLACE FUNCTION PARADATA
    (P_DATA IN VARCHAR2)
    RETURN VARCHAR2
IS
    V_DATA VARCHAR2(100);
    V_DIA  VARCHAR2(2);
    V_MES  VARCHAR2(100);
    V_ANO  VARCHAR2(4);
    
BEGIN

    V_DIA := SUBSTR(P_DATA, 1,2);
    V_MES := SUBSTR(P_DATA, 4,2);
    V_ANO := SUBSTR(P_DATA, 7);

    SELECT TO_CHAR(TO_DATE(V_MES, 'MM'), 'MONTH') INTO V_MES FROM DUAL;

    V_DATA := (V_DIA || ' DE ' || V_MES || ' DE ' || V_ANO);
    RETURN V_DATA;
    
END;

SELECT PARADATA('12/03/2008') FROM DUAL;