CREATE TABLE EMPREGADOS(
    CODIGO        NUMBER(5),
    NOME          VARCHAR(50),
    SOBRENOME     VARCHAR(50),
    DATA_ADMISSAO DATE,
    DATA_RECISAO  DATE,
    SALARIO       NUMBER(9,2),
    PROFISSAO     VARCHAR(40),
    DEPTO         NUMBER(3)
);

CREATE TABLE DEPARTAMENTOS (
    CODIGO    NUMBER(3),
    DESCRICAO VARCHAR(30)
);