--Crie uma view para o exercício 10 chamada view_ex10

CREATE VIEW VIEW_EX10 AS
    SELECT FAB.NOME AS FABRICANTE, CID.NOME AS CIDADE, BEB.DESCRICAO AS BEBIDA FROM FABRICANTES FAB
        JOIN CIDADES CID ON CID.CODIGO = FAB.CODCIDADE
        JOIN BEBIDAS BEB ON BEB.CODFABRICANTE = FAB.CODIGO;