--Mostre o nome do fabricante, a descrição da bebida e a descrição dos produtos que ele fabrica

SELECT FAB.NOME, BEB.DESCRICAO AS BEBIDA, PROD.DESCRICAO AS PRODUTOS FROM FABRICANTES FAB
    JOIN BEBIDAS  BEB  ON BEB.CODFABRICANTE  = FAB.CODIGO
    JOIN PRODUTOS PROD ON PROD.CODFABRICANTE = FAB.CODIGO