-- Crie as tabelas abaixo e insira os respectivos dados (OBRIGATORIO uso das seqüências criadas anteriormente)

CREATE TABLE CIDADES(
    CODIGO NUMBER PRIMARY KEY NOT NULL,
    NOME VARCHAR2(100)
)

SELECT * FROM CIDADES; --VERIFICA CRIAÇÃO DA TABELA

INSERT INTO CIDADES (CODIGO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 'Valinhos');
INSERT INTO CIDADES (CODIGO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 'Indaiatuba');
INSERT INTO CIDADES (CODIGO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 'Itupeva');
INSERT INTO CIDADES (CODIGO, NOME) VALUES (SEQ_CIDADE.NEXTVAL, 'Salto');

COMMIT;

SELECT * FROM CIDADES; -- VERIFICAR INSERÇÃO

CREATE TABLE FABRICANTES (
    CODIGO NUMBER PRIMARY KEY NOT NULL,
    NOME VARCHAR2(100),
    CODCIDADE NUMBER,
    CONSTRAINT FK_FABRICANTES FOREIGN KEY (CODCIDADE) REFERENCES CIDADES(CODIGO)
)

SELECT * FROM FABRICANTES; --VERIFICA CRIAÇÃO DA TABELA

INSERT INTO FABRICANTES (CODIGO, NOME, CODCIDADE) VALUES (SEQ_FABRICANTES.NEXTVAL, 'ValBebidas', 1);
INSERT INTO FABRICANTES (CODIGO, NOME, CODCIDADE) VALUES (SEQ_FABRICANTES.NEXTVAL, 'Indaiá', 3);
INSERT INTO FABRICANTES (CODIGO, NOME, CODCIDADE) VALUES (SEQ_FABRICANTES.NEXTVAL, 'Indaiá', 2);
INSERT INTO FABRICANTES (CODIGO, NOME, CODCIDADE) VALUES (SEQ_FABRICANTES.NEXTVAL, 'Indaiá', 4);
INSERT INTO FABRICANTES (CODIGO, NOME, CODCIDADE) VALUES (SEQ_FABRICANTES.NEXTVAL, 'Chapadão Ltda', 2);

COMMIT;

SELECT * FROM FABRICANTES; -- VERIFICAR INSERÇÃO

CREATE TABLE BEBIDAS (
    CODIGO NUMBER PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR2(100),
    CODFABRICANTE NUMBER,
    CONSTRAINT FK_CODFABRICANTE FOREIGN KEY (CODFABRICANTE) REFERENCES FABRICANTES(CODIGO)
)

SELECT * FROM BEBIDAS  --VERIFICA CRIAÇÃO DA TABELA

INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'Cerveja', 1);
INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'Cerveja', 5);
INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'Água com gás', 2);
INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'Absinto', 5);
INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'Pinga com Mel', 5);
INSERT INTO BEBIDAS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_BEBIDAS.NEXTVAL, 'HiFi', 5);

COMMIT;

SELECT * FROM BEBIDAS; -- VERIFICAR INSERÇÃO

CREATE TABLE PRODUTOS (
    CODIGO NUMBER PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(100),
    CODFABRICANTE NUMBER,
    CONSTRAINT FK_CODFABRICANTE_PRODUTOS FOREIGN KEY (CODFABRICANTE) REFERENCES FABRICANTES(CODIGO)
)

SELECT * FROM PRODUTOS; --VERIFICA CRIAÇÃO DA TABELA

INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Café', 1);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Cerveja', 2);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Amendoim', 3);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Pizza', 4);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Baguete', 5);
INSERT INTO PRODUTOS (CODIGO, DESCRICAO, CODFABRICANTE) VALUES (SEQ_PRODUTOS.NEXTVAL, 'Bolo de Pinga', 5);

COMMIT;

SELECT * FROM PRODUTOS; -- VERIFICAR INSERÇÃO